### ISSUE TITLE
Programmatically scroll to section header

### ISSUE THREAD

**Issue by codyrotwein** [applidium/HeaderListView#41]
Is there any way to programmatically scroll to a particular section header? I have buttons along the top of my ListView which represent the different section headers, and I want to scroll to the appropriate section upon tapping them. Is this possible?

**Comment by dimitrireef** [comment]
did you find a solution for this issue ?

**Comment by codyrotwein** [comment]
Not yet.

**Comment by tokou** [comment]
Hello,

You should call [#smoothScrollToPosition(int)](http://developer.android.com/reference/android/widget/ListView.html#smoothScrollToPosition(int)) or [#setSelection(int)](http://developer.android.com/reference/android/widget/AdapterView.html#setSelection(int)) on the underlying ListView while passing numberOfCellsBeforeSection(int section) as argument.
