### ISSUE TITLE
Populating header and row dynamically

### ISSUE THREAD

**Issue by dimitrireef** [applidium/HeaderListView#42]
Hello how can i inject the items below inside SectionAdapter ?

        List<Item> items = new ArrayList<Item>();
        items.add(new Header("Header 1"));
        items.add(new ListItem("Text 1", "Rabble rabble"));
        items.add(new ListItem("Text 2", "Rabble rabble"));
        items.add(new ListItem("Text 3", "Rabble rabble"));
        items.add(new ListItem("Text 4", "Rabble rabble"));

        items.add(new Header("Header 2"));
        items.add(new ListItem("Text 5", "Rabble rabble"));
        items.add(new ListItem("Text 6", "Rabble rabble"));
        items.add(new ListItem("Text 7", "Rabble rabble"));
        items.add(new ListItem("Text 8", "Rabble rabble"));
        items.add(new ListItem("Text 9", "Rabble rabble"));
        items.add(new ListItem("Text 10", "Rabble rabble"));

**Comment by tokou** [comment]
HeaderListView is based on Android's ListView that uses the Adapter mechanism to get populated. Please refer to http://developer.android.com/reference/android/widget/BaseAdapter.html for more information.

**Comment by dimitrireef** [comment]
tried several methods but still unable to populate dynamic header and rows.
